name = "oscillyx-signature-service"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "OSCILLYX_KV"
id = "your-kv-namespace-id"

[env.production]
name = "oscillyx-signature-service-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "OSCILLYX_KV"
id = "your-production-kv-namespace-id"